CREATE DATABASE $PRETALX_DB_NAME
   DEFAULT CHARACTER SET utf8mb4 DEFAULT COLLATE utf8mb4_unicode_ci;
CREATE USER '$PRETALX_DB_USER'@'%' IDENTIFIED BY '$PRETALX_DB_PASS';
GRANT ALL PRIVILEGES ON $PRETALX_DB_NAME.* TO '$PRETALX_DB_USER'@'%';
FLUSH PRIVILEGES;
